//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8009
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.8009.
// 
namespace SmartDeviceProject1.servicenapresa {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GoMobileWSSoap", Namespace="http://www.napresa.com.mx/")]
    public partial class GoMobileWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public GoMobileWS() {
            this.Url = "http://192.168.0.229/NapresaService/Services/GoMobileWS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.napresa.com.mx/sendEmail", RequestNamespace="http://www.napresa.com.mx/", ResponseNamespace="http://www.napresa.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsError sendEmail(sendEmail_model obj) {
            object[] results = this.Invoke("sendEmail", new object[] {
                        obj});
            return ((clsError)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendEmail(sendEmail_model obj, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendEmail", new object[] {
                        obj}, callback, asyncState);
        }
        
        /// <remarks/>
        public clsError EndsendEmail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((clsError)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.napresa.com.mx/sendEmailTest", RequestNamespace="http://www.napresa.com.mx/", ResponseNamespace="http://www.napresa.com.mx/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sendEmailTest(string vTo, string vFrom) {
            object[] results = this.Invoke("sendEmailTest", new object[] {
                        vTo,
                        vFrom});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsendEmailTest(string vTo, string vFrom, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("sendEmailTest", new object[] {
                        vTo,
                        vFrom}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsendEmailTest(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.napresa.com.mx/")]
    public partial class sendEmail_model {
        
        private string subjectField;
        
        private string toField;
        
        private string fromField;
        
        private string bodyField;
        
        private string subjectField1;
        
        private string toField1;
        
        private string fromField1;
        
        private string bodyField1;
        
        /// <remarks/>
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        public string subject {
            get {
                return this.subjectField1;
            }
            set {
                this.subjectField1 = value;
            }
        }
        
        /// <remarks/>
        public string to {
            get {
                return this.toField1;
            }
            set {
                this.toField1 = value;
            }
        }
        
        /// <remarks/>
        public string from {
            get {
                return this.fromField1;
            }
            set {
                this.fromField1 = value;
            }
        }
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField1;
            }
            set {
                this.bodyField1 = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.napresa.com.mx/")]
    public partial class clsError {
        
        private bool successfulField;
        
        private string detailsField;
        
        private bool successfulField1;
        
        private string detailsField1;
        
        /// <remarks/>
        public bool Successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
            }
        }
        
        /// <remarks/>
        public string Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public bool successful {
            get {
                return this.successfulField1;
            }
            set {
                this.successfulField1 = value;
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField1;
            }
            set {
                this.detailsField1 = value;
            }
        }
    }
}
